config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/contact'

  get 'page/about'

  devise_for :users
  resources :rtes
devise_scope :user do
authenticated do
root to:'rtes#index', as: :authenticated_root
end
root to:"devise/sessions#new"
end

end

app/models/rte.rb
class Rte < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
before_action :authenticate_user!, only: [:contact]
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/rtes_controller.rb
class RtesController < ApplicationController
  before_action :set_rte, only: [:show, :edit, :update, :destroy]

  # GET /rtes
  # GET /rtes.json
  def index
    @rtes = Rte.all
  end

  # GET /rtes/1
  # GET /rtes/1.json
  def show
  end

  # GET /rtes/new
  def new
    @rte = Rte.new
  end

  # GET /rtes/1/edit
  def edit
  end

  # POST /rtes
  # POST /rtes.json
  def create
    @rte = Rte.new(rte_params)

    respond_to do |format|
      if @rte.save
        format.html { redirect_to @rte, notice: 'Rte was successfully created.' }
        format.json { render :show, status: :created, location: @rte }
      else
        format.html { render :new }
        format.json { render json: @rte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rtes/1
  # PATCH/PUT /rtes/1.json
  def update
    respond_to do |format|
      if @rte.update(rte_params)
        format.html { redirect_to @rte, notice: 'Rte was successfully updated.' }
        format.json { render :show, status: :ok, location: @rte }
      else
        format.html { render :edit }
        format.json { render json: @rte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rtes/1
  # DELETE /rtes/1.json
  def destroy
    @rte.destroy
    respond_to do |format|
      format.html { redirect_to rtes_url, notice: 'Rte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rte
      @rte = Rte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rte_params
      params.require(:rte).permit(:name, :place, :date, :organiser, :volunteer, :school)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rtes_helper.rb
module RtesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ngoeventmanagement1App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<%= link_to "home", page_home_path %><br>
<%= link_to "contact", page_contact_path %><br>
<%= link_to "about", page_about_path %><br>



<%= link_to "Sign out", destroy_user_session_path, method: :delete %><br>
<% else %>
<%= link_to "Sign in", new_user_session_path %><br>
<%= link_to "Sign up", new_user_registration_path %><br>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/rte/_form.html.erb
<%= form_for @rte, :html => { :class => "form-horizontal rte" } do |f| %>

  <% if @rte.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rte.errors.count, "error") %> prohibited this rte from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rte.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :place, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :place, :class => 'form-control' %>
    </div>
    <%=f.error_span(:place) %>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date) %>
  </div>
  <div class="form-group">
    <%= f.label :organiser, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :organiser, :class => 'form-control' %>
    </div>
    <%=f.error_span(:organiser) %>
  </div>
  <div class="form-group">
    <%= f.label :volunteer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :volunteer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:volunteer) %>
  </div>
  <div class="form-group">
    <%= f.label :school, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :school, :class => 'form-control' %>
    </div>
    <%=f.error_span(:school) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rtes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/rte/edit.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rte/index.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:organiser) %></th>
      <th><%= model_class.human_attribute_name(:volunteer) %></th>
      <th><%= model_class.human_attribute_name(:school) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rtes.each do |rte| %>
      <tr>
        <td><%= link_to rte.id, rte_path(rte) %></td>
        <td><%= rte.name %></td>
        <td><%= rte.place %></td>
        <td><%= rte.date %></td>
        <td><%= rte.organiser %></td>
        <td><%= rte.volunteer %></td>
        <td><%= rte.school %></td>
        <td><%=l rte.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rte_path(rte), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rte_path(rte),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rte_path,
            :class => 'btn btn-primary' %>

app/views/rte/new.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rte/show.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @rte.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @rte.place %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @rte.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organiser) %>:</strong></dt>
  <dd><%= @rte.organiser %></dd>
  <dt><strong><%= model_class.human_attribute_name(:volunteer) %>:</strong></dt>
  <dd><%= @rte.volunteer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:school) %>:</strong></dt>
  <dd><%= @rte.school %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              rtes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rte_path(@rte), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rte_path(@rte),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/rtes/_form.html.erb
<%= form_for @rte, :html => { :class => "form-horizontal rte" } do |f| %>

  <% if @rte.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rte.errors.count, "error") %> prohibited this rte from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rte.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :place, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :place, :class => 'form-control' %>
    </div>
    <%=f.error_span(:place) %>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:date) %>
  </div>
  <div class="form-group">
    <%= f.label :organiser, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :organiser, :class => 'form-control' %>
    </div>
    <%=f.error_span(:organiser) %>
  </div>
  <div class="form-group">
    <%= f.label :volunteer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :volunteer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:volunteer) %>
  </div>
  <div class="form-group">
    <%= f.label :school, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :school, :class => 'form-control' %>
    </div>
    <%=f.error_span(:school) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rtes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/rtes/edit.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rtes/index.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:place) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:organiser) %></th>
      <th><%= model_class.human_attribute_name(:volunteer) %></th>
      <th><%= model_class.human_attribute_name(:school) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rtes.each do |rte| %>
      <tr>
        <td><%= link_to rte.id, rte_path(rte) %></td>
        <td><%= rte.name %></td>
        <td><%= rte.place %></td>
        <td><%= rte.date %></td>
        <td><%= rte.organiser %></td>
        <td><%= rte.volunteer %></td>
        <td><%= rte.school %></td>
        <td><%=l rte.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rte_path(rte), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rte_path(rte),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rte_path,
            :class => 'btn btn-primary' %>

app/views/rtes/new.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rtes/show.html.erb
<%- model_class = Rte -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @rte.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>
  <dd><%= @rte.place %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @rte.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organiser) %>:</strong></dt>
  <dd><%= @rte.organiser %></dd>
  <dt><strong><%= model_class.human_attribute_name(:volunteer) %>:</strong></dt>
  <dd><%= @rte.volunteer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:school) %>:</strong></dt>
  <dd><%= @rte.school %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              rtes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rte_path(@rte), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rte_path(@rte),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>